# Generated by Django 5.2.6 on 2025-11-04 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_remove_answer_answer_text_answer_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='created_at',
        ),
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('quiz_attempt', 'question')},
        ),
    ]
